nohup python rbc.py hpvm1_hpracdb &
nohup python rbc.py hpvm1_ora111db &
nohup python rbc.py hpvm1_orafsdb &
nohup python rbc.py bb6aix3_bb12rcdb &
nohup python rbc.py ore-rhel11g-1_oriondb &
nohup python rbc.py ndm4-vm_ort205db &
nohup python rbc.py ndm4-vm_tengfs &
nohup python rbc.py sun08-03_sol12pdb &
nohup python rbc.py nstlpar24_autodb &
nohup python rbc.py nstlpar24_ora111db &
nohup python rbc.py nstlpar24_ten205db &
nohup python rbc.py rh66orarac1_demondb &
nohup python rbc.py rh66orarac1_ora111db &
