nohup python rbc.py hpvm1_hpracdb_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py atmlpar9_ix11R2db_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py bb6aix3_bb12rcdb_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py ore-rhel11g-1_oriondb_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py atmlpar4_atmlpar4fs_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py rh66orarac1_ora111db_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py sun08-03_sol12pdb_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py nstlpar24_ora111db_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py sun08-01_ora111db_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py hpdbvm21_hp121pdb_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py ndm4-vm_tengfs_mounts_nonlogsmart_osauth_layer1 &
nohup python rbc.py hpvm1_orafsdb_mounts_nonlogsmart_osauth_layer2 &
nohup python rbc.py atmlpar9_ax12cdb_mounts_nonlogsmart_osauth_layer2 &
nohup python rbc.py atmlpar4_atm4longname_mounts_nonlogsmart_osauth_layer2 &
nohup python rbc.py rh66orarac1_demondb_mounts_nonlogsmart_osauth_layer2 &
nohup python rbc.py sun08-03_sol11gdb_mounts_nonlogsmart_osauth_layer2 &
nohup python rbc.py nstlpar24_autodb_mounts_nonlogsmart_osauth_layer2 &
nohup python rbc.py sun08-01_soldb_mounts_nonlogsmart_osauth_layer2 &
nohup python rbc.py hpdbvm21_hp11R2db_mounts_nonlogsmart_osauth_layer2 &
nohup python rbc.py ndm4-vm_ort205db_mounts_nonlogsmart_osauth_layer2 &
nohup python rbc.py nstlpar24_ora112fsdb_mounts_nonlogsmart_osauth_layer3 &
nohup python rbc.py sun08-01_solfsdb_mounts_nonlogsmart_osauth_layer3 &
nohup python rbc.py hpvm1_hpracdb_mounts_dbauth_layer1 &
nohup python rbc.py atmlpar9_ix11R2db_mounts_dbauth_layer1 &
nohup python rbc.py bb6aix3_bb12rcdb_mounts_dbauth_layer1 &
nohup python rbc.py ore-rhel11g-1_oriondb_mounts_dbauth_layer1 &
nohup python rbc.py atmlpar4_atmlpar4fs_mounts_dbauth_layer1 &
nohup python rbc.py rh66orarac1_ora111db_mounts_dbauth_layer1 &
nohup python rbc.py sun08-03_sol12pdb_mounts_dbauth_layer1 &
nohup python rbc.py nstlpar24_ora111db_mounts_dbauth_layer1 &
nohup python rbc.py sun08-01_ora111db_mounts_dbauth_layer1 &
nohup python rbc.py hpdbvm21_hp121pdb_mounts_dbauth_layer1 &
nohup python rbc.py ndm4-vm_tengfs_mounts_dbauth_layer1 &
nohup python rbc.py hpvm1_orafsdb_mounts_dbauth_layer2 &
nohup python rbc.py atmlpar9_ax12cdb_mounts_dbauth_layer2 &
nohup python rbc.py atmlpar4_atm4longname_mounts_dbauth_layer2 &
nohup python rbc.py rh66orarac1_demondb_mounts_dbauth_layer2 &
nohup python rbc.py sun08-03_sol11gdb_mounts_dbauth_layer2 &
nohup python rbc.py nstlpar24_autodb_mounts_dbauth_layer2 &
nohup python rbc.py sun08-01_soldb_mounts_dbauth_layer2 &
nohup python rbc.py hpdbvm21_hp11R2db_mounts_dbauth_layer2 &
nohup python rbc.py ndm4-vm_ort205db_mounts_dbauth_layer2 &
nohup python rbc.py nstlpar24_ora112fsdb_mounts_dbauth_layer3 &
nohup python rbc.py sun08-01_solfsdb_mounts_dbauth_layer3 &
nohup python rbc.py hpvm1_hpracdb_mounts_default_layer1 &
nohup python rbc.py atmlpar9_ix11R2db_mounts_default_layer1 &
nohup python rbc.py bb6aix3_bb12rcdb_mounts_default_layer1 &
nohup python rbc.py ore-rhel11g-1_oriondb_mounts_default_layer1 &
nohup python rbc.py atmlpar4_atmlpar4fs_mounts_default_layer1 &
nohup python rbc.py rh66orarac1_ora111db_mounts_default_layer1 &
nohup python rbc.py sun08-03_sol12pdb_mounts_default_layer1 &
nohup python rbc.py nstlpar24_ora111db_mounts_default_layer1 &
nohup python rbc.py sun08-01_ora111db_mounts_default_layer1 &
nohup python rbc.py hpdbvm21_hp121pdb_mounts_default_layer1 &
nohup python rbc.py ndm4-vm_tengfs_mounts_default_layer1 &
nohup python rbc.py hpvm1_orafsdb_mounts_default_layer2 &
nohup python rbc.py atmlpar9_ax12cdb_mounts_default_layer2 &
nohup python rbc.py atmlpar4_atm4longname_mounts_default_layer2 &
nohup python rbc.py rh66orarac1_demondb_mounts_default_layer2 &
nohup python rbc.py sun08-03_sol11gdb_mounts_default_layer2 &
nohup python rbc.py nstlpar24_autodb_mounts_default_layer2 &
nohup python rbc.py sun08-01_soldb_mounts_default_layer2 &
nohup python rbc.py hpdbvm21_hp11R2db_mounts_default_layer2 &
nohup python rbc.py ndm4-vm_ort205db_mounts_default_layer2 &
nohup python rbc.py nstlpar24_ora112fsdb_mounts_default_layer3 &
nohup python rbc.py sun08-01_solfsdb_mounts_default_layer3 &
nohup python rbc.py hpvm1_hpracdb_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py atmlpar9_ix11R2db_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py bb6aix3_bb12rcdb_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py ore-rhel11g-1_oriondb_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py atmlpar4_atmlpar4fs_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py rh66orarac1_ora111db_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py sun08-03_sol12pdb_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py nstlpar24_ora111db_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py sun08-01_ora111db_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py hpdbvm21_hp121pdb_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py ndm4-vm_tengfs_mounts_nonlogsmart_dbauth_layer1 &
nohup python rbc.py hpvm1_orafsdb_mounts_nonlogsmart_dbauth_layer2 &
nohup python rbc.py atmlpar9_ax12cdb_mounts_nonlogsmart_dbauth_layer2 &
nohup python rbc.py atmlpar4_atm4longname_mounts_nonlogsmart_dbauth_layer2 &
nohup python rbc.py rh66orarac1_demondb_mounts_nonlogsmart_dbauth_layer2 &
nohup python rbc.py sun08-03_sol11gdb_mounts_nonlogsmart_dbauth_layer2 &
nohup python rbc.py nstlpar24_autodb_mounts_nonlogsmart_dbauth_layer2 &
nohup python rbc.py sun08-01_soldb_mounts_nonlogsmart_dbauth_layer2 &
nohup python rbc.py hpdbvm21_hp11R2db_mounts_nonlogsmart_dbauth_layer2 &
nohup python rbc.py ndm4-vm_ort205db_mounts_nonlogsmart_dbauth_layer2 &
nohup python rbc.py nstlpar24_ora112fsdb_mounts_nonlogsmart_dbauth_layer3 &
nohup python rbc.py sun08-01_solfsdb_mounts_nonlogsmart_dbauth_layer3 &
