# Fill in with absolute paths to your resources
aliases_file: /home/ore/aliases
inv_dir: /home/ore/inv
log_dir: /home/ore/logs
framework3_dir: /home/robo/dev/framework3

# Place all test result logs in dated logs directory
auto_archive_logs: True
# Email test results
email_results: True
only_email_fails: False
recipients: ['leif.taylor@actifio.com']

# Docker settings
docker_repo: brianwilliams/framework3
drobot_command: docker run -i --privileged=true -v <framework3_dir>:/home/testing -v <inv_dir>:/home/testing/robot/inv <docker_repo> robot -d . --log <HTMLFILE> --output <XMLFILE> --loglevel DEBUG:INFO
